[package]
name = "win_hid_info"
version = "0.1.0"
authors = ["Nick Cardin <nick@cardin.email>"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["setupapi", "hidclass", "errhandlingapi", "fileapi", "handleapi", "hidsdi", "winbase"] }